#! /bin/sh

######################################################################
TESTID="FT1-2-3-2"
CATEGORY="accident causes no failover"
SECTION="fsn accident"
TITLE="network down with slave to fsn"
######################################################################

. ./FT-common

ft_setup()
{
	IFUP_PATH=/sbin/ifup
	IFDOWN_PATH=/sbin/ifdown

	return $FT_RESULT_PASS
}

ft_main()
{
	RESULT=$FT_RESULT_PASS

	ssh $gfsd2_CTRL_ADDRESS sudo $IFDOWN_PATH $gfsd2_GFARM_IF \
		|| RESULT=$FT_RESULT_FAIL
	ft_checkpoint 1 "ifdown $gfsd2_GFARM_IF on $gfsd2" $RESULT
	[ $RESULT -eq $FT_RESULT_PASS ] || return $RESULT

	ft_check_mail \
		"Can't get master metadata server name on $gfsd2" && \
	ft_check_mail \
		"Gfarm metadata server list is not available on $gfsd2" && \
	ft_check_mail \
		"Reachability failed on $gfsd2" && \
	ft_check_mail \
		"Backchannel failed on $gfsd2"
	[ $? -eq 0 ] || RESULT=$FT_RESULT_FAIL
	ft_checkpoint 2 "receive a mail" $RESULT
	[ $RESULT -eq $FT_RESULT_PASS ] || return $RESULT
	ft_truncate_mbox


	ssh $gfsd2_CTRL_ADDRESS sudo $IFUP_PATH $gfsd2_GFARM_IF \
		|| RESULT=$FT_RESULT_FAIL
	ft_checkpoint 3 "ifup $gfsd2_GFARM_IF on $gfsd2" $RESULT
	[ $RESULT -eq $FT_RESULT_PASS ] || return $RESULT

	ft_check_mail \
		"Re: Can't get master metadata server name on $gfsd2" && \
	ft_check_mail \
		"Re: Gfarm metadata server list is not available on $gfsd2" && \
	ft_check_mail \
		"Re: Reachability failed on $gfsd2" && \
	ft_check_mail \
		"Re: Backchannel failed on $gfsd2"
	[ $? -eq 0 ] || RESULT=$FT_RESULT_FAIL
	ft_checkpoint 4 "receive a mail" $RESULT
	[ $RESULT -eq $FT_RESULT_PASS ] || return $RESULT
	ft_truncate_mbox

	return $RESULT
}

ft_teardown()
{
	ssh $gfsd2_CTRL_ADDRESS sudo $IFUP_PATH $gfsd2_GFARM_IF
	return $FT_RESULT_PASS
}
	
ft_run "$TESTID" "$TITLE"
