#! /bin/sh

######################################################################
TESTID="FT2-2-2-3"
CATEGORY="2 point accident"
SECTION="2 internal accident"
TITLE="master gfmd down and master candidate MDS network down"
######################################################################

. ./FT-common

ft_setup()
{
	IFDOWN=/sbin/ifdown
	IFUP=/sbin/ifup
	return $FT_RESULT_PASS
}

ft_main()
{
	RESULT=$FT_RESULT_PASS

	ssh $gfmd2_CTRL_ADDRESS sudo $IFDOWN $gfmd2_GFARM_IF \
		|| RESULT=$FT_RESULT_FAIL
	ft_checkpoint 1 "ifdown $gfmd2_GFARM_IF on $gfmd2" $RESULT
	[ $RESULT -eq $FT_RESULT_PASS ] || return $RESULT

	$gfservice stop-gfmd gfmd1 \
		|| RESULT=$FT_RESULT_FAIL
	ft_checkpoint 2 "stop master gfmd on $gfmd1" $RESULT
	[ $RESULT -eq $FT_RESULT_PASS ] || return $RESULT

	ft_check_mail "gfmd does not listen on $gfmd1" \
		|| RESULT=$FT_RESULT_FAIL
	ft_checkpoint 3 "receive a mail" $RESULT
	[ $RESULT -eq $FT_RESULT_PASS ] || return $RESULT

	ft_check_mail "Re: gfmd does not listen on $gfmd1" \
		|| RESULT=$FT_RESULT_FAIL
	ft_checkpoint 4 "receive a mail" $RESULT
	[ $RESULT -eq $FT_RESULT_PASS ] || return $RESULT

	return $RESULT
}

ft_teardown()
{
	ssh $gfmd2_CTRL_ADDRESS sudo $IFUP $gfmd2_GFARM_IF
	ft_reset_gfmd
	return $FT_RESULT_PASS
}
	
ft_run "$TESTID" "$TITLE"
