#! /bin/sh

########################################################################
TESTID="FT3-1-2-2"
CATEGORY="2 point accident"
SECTION="2 internal accident"
TITLE="gfmd and zabbix agent on master MDS are down"
########################################################################

. ./FT-common

ft_setup()
{
	FT_MAIL_TIMEOUT=900

	return $FT_RESULT_PASS
}

ft_main()
{
	RESULT=$FT_RESULT_PASS

	$gfservice stop-gfmd gfmd1 \
		|| RESULT=$FT_RESULT_FAIL
	ft_checkpoint 1 "stop gfmd on $gfmd1" $RESULT
	[ $RESULT -eq $FT_RESULT_PASS ] || return $RESULT

	ssh $gfmd1 sudo /etc/init.d/zabbix-agent stop \
		|| RESULT=$FT_RESULT_FAIL
	ft_checkpoint 2 "stop zabbix-agent on $gfmd" $RESULT
	[ $RESULT -eq $FT_RESULT_PASS ] || return $RESULT

	ft_check_mail "zabbix agent is not running on $gfmd1" \
		|| RESULT=$FT_RESULT_FAIL
	ft_checkpoint 3 "receive a mail" $RESULT
	[ $RESULT -eq $FT_RESULT_PASS ] || return $RESULT

	return $RESULT
}

ft_teardown()
{
	ft_reset_gfmd
	ssh $gfmd1 sudo /etc/init.d/zabbix-agent start
	return $FT_RESULT_PASS
}

ft_run "$TESTID" "$TITLE"
