# $Id: Makefile 2390 2006-01-20 05:21:54Z tatebe $

top_builddir = ../../../..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/makes/var.mk

htmldir=$(default_htmldir)/en/user

HTML =	index.html \
	nfs-gfarmfs.html \
	samba-gfarmfs.html
# XXX not translated yet
#	export-gfarm.html \
#	samba-hook.html

include $(top_srcdir)/makes/html.mk
