#! /bin/sh

######################################################################
TESTID="FT1-2-3-3"
CATEGORY="accident causes no failover"
SECTION="fsn accident"
TITLE="gfsd warning and error"
######################################################################

. ./FT-common

ft_setup()
{
	zabbix_sender -z $zabbix1 -s $gfsd1 -k 'log[{$GFARM_LOGFILE},"\sgfsd\[[0-9]+\]:\s+<err>",UTF-8]' -o RECOVERED
	zabbix_sender -z $zabbix1 -s $gfsd1 -k 'log[{$GFARM_LOGFILE},"\sgfsd\[[0-9]+\]:\s+<warning>",UTF-8]' -o RECOVERED
	return $FT_RESULT_PASS
}

ft_main()
{
	RESULT=$FT_RESULT_PASS

	ADDITIONAL_TIME=600
	FT_MAIL_TIMEOUT=`expr $FT_MAIL_TIMEOUT + $ADDITIONAL_TIME`
	
	ssh $gfsd1 logger -p $FT_SYSLOG_FACILITY.err \
		-t "gfsd[9999]" "\<err\> unknown error" && \
	ssh $gfsd1 logger -p $FT_SYSLOG_FACILITY.warning \
		-t "gfsd[9999]" "\<warning\> unknown warning" || \
	RESULT=$FT_RESULT_FAIL
	ft_checkpoint 1 "logging error on $gfsd1" $RESULT
	[ $RESULT -eq $FT_RESULT_PASS ] || return $RESULT

	ft_check_mail "gfsd error message in /var/log/messages on $gfsd1" &&\
	ft_check_mail "gfsd warning message in /var/log/messages on $gfsd1" ||\
	RESULT=$FT_RESULT_FAIL
	ft_checkpoint 2 "receive mails" $RESULT
	[ $RESULT -eq $FT_RESULT_PASS ] || return $RESULT

	zabbix_sender -v -z $zabbix1 -s $gfsd1 -k 'log[{$GFARM_LOGFILE},"\sgfsd\[[0-9]+\]:\s+<err>",UTF-8]' -o RECOVERED
	zabbix_sender -v -z $zabbix1 -s $gfsd1 -k 'log[{$GFARM_LOGFILE},"\sgfsd\[[0-9]+\]:\s+<warning>",UTF-8]' -o RECOVERED || RESULT=$FT_RESULT_FAIL
	ft_checkpoint 3 "clear log" $RESULT
	[ $RESULT -eq $FT_RESULT_PASS ] || return $RESULT

	ft_check_mail "Re: gfsd error message in /var/log/messages on $gfsd1" &&\
	ft_check_mail "Re: gfsd warning message in /var/log/messages on $gfsd1" ||\
	RESULT=$FT_RESULT_FAIL
	ft_checkpoint 4 "receive mails" $RESULT
	[ $RESULT -eq $FT_RESULT_PASS ] || return $RESULT

	return $RESULT
}

ft_teardown()
{
	return $FT_RESULT_PASS
}
	
ft_run "$TESTID" "$TITLE"
