# $Id: Makefile 98 2002-05-07 01:11:37Z soda $

top_objdir = ../../..
top_srcdir = $(top_objdir)
srcdir = .

include $(top_srcdir)/makes/var.mk
include $(srcdir)/../Makefile.inc

MAN = gfmd.8 gfsd.8

include $(top_srcdir)/makes/man.mk
