#! /bin/sh

########################################################################
TESTID="FT3-1-2-3"
CATEGORY="2 point accident"
SECTION="2 internal accident"
TITLE="zabbix agents on master and master candidate are down"
########################################################################

. ./FT-common

ft_setup()
{
	FT_MAIL_TIMEOUT=900

	return $FT_RESULT_PASS
}

ft_main()
{
	RESULT=$FT_RESULT_PASS

	ft_checkpoint 1 "find master candidate gfmd" $RESULT
	[ $RESULT -eq $FT_RESULT_PASS ] || return $RESULT

	ssh $gfmd1 sudo /etc/init.d/zabbix-agent stop \
		|| RESULT=$FT_RESULT_FAIL
	ft_checkpoint 2 "stop zabbix-agent on $gfmd1" $RESULT
	[ $RESULT -eq $FT_RESULT_PASS ] || return $RESULT

	ssh $gfmd2 sudo /etc/init.d/zabbix-agent stop \
		|| RESULT=$FT_RESULT_FAIL
	ft_checkpoint 3 "stop zabbix-agent on $gfmd2" $RESULT
	[ $RESULT -eq $FT_RESULT_PASS ] || return $RESULT

	ft_check_mail "zabbix agent is not running on $gfmd1" \
		|| RESULT=$FT_RESULT_FAIL
	ft_checkpoint 4 "receive a mail" $RESULT
	[ $RESULT -eq $FT_RESULT_PASS ] || return $RESULT

	ft_check_mail "zabbix agent is not running on $gfmd2" \
		|| RESULT=$FT_RESULT_FAIL
	ft_checkpoint 5 "receive a mail" $RESULT
	[ $RESULT -eq $FT_RESULT_PASS ] || return $RESULT

	return $RESULT
}

ft_teardown()
{
	ssh $gfmd1 sudo /etc/init.d/zabbix-agent start
	ssh $gfmd2 sudo /etc/init.d/zabbix-agent start
	ft_reset_gfmd
	return $FT_RESULT_PASS
}

ft_run "$TESTID" "$TITLE"
