# $Id: Makefile 6189 2012-03-29 04:26:14Z yuichironaito $

top_builddir = ../../..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/makes/var.mk

SCRIPTS = $(srcdir)/gfpcopy-test.sh

include $(top_srcdir)/makes/script.mk
