#! /bin/sh

######################################################################
TESTID="FT2-2-1-1"
CATEGORY="2 point accident"
SECTION="internal accident and network down"
TITLE="master gfmd down with observer network down"
######################################################################

. ./FT-common

ft_setup()
{
	IFUP_PATH=/sbin/ifup
	IFDOWN_PATH=/sbin/ifdown
	if [ `hostname` = $zabbix2 ]; then
		zabbix=$zabbix2
		zabbix_GFARM_IF=$zabbix2_GFARM_IF
		zabbix_CTRL_ADDRESS=$zabbix2_CTRL_ADDRESS
	else
		zabbix=$zabbix1
		zabbix_GFARM_IF=$zabbix1_GFARM_IF
		zabbix_CTRL_ADDRESS=$zabbix1_CTRL_ADDRESS
	fi

	return $FT_RESULT_PASS
}

ft_main()
{
	RESULT=$FT_RESULT_PASS

	$gfservice stop-gfmd gfmd1 \
		|| RESULT=$FT_RESULT_FAIL
	ft_checkpoint 1 "stop gfmd on $gfmd1" $RESULT
	[ $RESULT -eq $FT_RESULT_PASS ] || return $RESULT

	sudo $IFDOWN_PATH $zabbix_GFARM_IF \
		|| RESULT=$FT_RESULT_FAIL
	ft_checkpoint 2 "ifdown $zabbix_GFARM_IF on $zabbix" $RESULT
	[ $RESULT -eq $FT_RESULT_PASS ] || return $RESULT

	ft_check_mails \
		"$gfmd1 is unreachable" \
		"$gfmd2 is unreachable" \
		"$gfmd3 is unreachable" \
		"$gfsd1 is unreachable" \
		"$gfsd2 is unreachable" \
		|| RESULT=$FT_RESULT_FAIL
	ft_checkpoint 3 "receive a mail" $RESULT
	[ $RESULT -eq $FT_RESULT_PASS ] || return $RESULT

	return $RESULT
}

ft_teardown()
{
	sudo $IFUP_PATH $zabbix_GFARM_IF
	ft_reset_gfmd
	return $FT_RESULT_PASS
}
	
ft_run "$TESTID" "$TITLE"
